name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Pack NuGet packages
      run: dotnet pack --no-build --configuration Release

    - name: Publish NuGet packages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        for nupkg in $(find . -name '*.nupkg'); do
          PACKAGE_NAME=$(basename "$nupkg" .nupkg)
          PACKAGE_VERSION=$(dotnet nuget list source -s https://api.nuget.org/v3/index.json | grep "$PACKAGE_NAME" | awk '{print $2}')
          LOCAL_VERSION=$(dotnet nuget list source -s ./ | grep "$PACKAGE_NAME" | awk '{print $2}')
          if [ "$(printf '%s\n' "$PACKAGE_VERSION" "$LOCAL_VERSION" | sort -V | head -n1)" != "$LOCAL_VERSION" ]; then
            dotnet nuget push "$nupkg" -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json;
          else
            echo "Skipping $nupkg as the version is not newer than the published version."
          fi
        done